# Generated by Django 5.2.3 on 2025-06-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_name', models.CharField(blank=True, max_length=100)),
                ('manual_surname', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('tag', models.CharField(choices=[('meet', 'Meet'), ('reminder', 'Reminder'), ('event', 'Event')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_app.person')),
            ],
        ),
    ]
